language: php

php:
    - 5.6
    - 7.0

sudo: false

matrix:
  fast_finish: true

cache:
  - apt

addons:
  apt:
    packages:
      - nginx
      - realpath
    hosts:
      - api.shwrm.net
install:
#  - composer install
  - travis/install-nginx.sh

script:
  - curl -vsf 'http://localhost:8080/hello.php' &> /dev/stdout
  - cat /tmp/error.log
